/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;

/**
 *
 * @author David y Laura
 */
public class PomodoroStudy extends javax.swing.JFrame {
    
    public AudioStream audio1;
    public AudioStream audio2;
    

    /**
     * Creates new form PomodoroStudy
     */
    public PomodoroStudy() {
        initComponents();
        this.getContentPane().setBackground(Color.WHITE);
        t = new Timer(1000, acciones);
        t2 = new Timer(1000, acciones2);
        t3 = new Timer (1000,acciones3);
        jBtnDetener.setEnabled(false);
        jBtnPausar.setEnabled(false);
        jBtnReanudar.setEnabled(false);
        jLabel2.setIcon(new ImageIcon("D:\\DAVID\\gifparado.png"));
        //jLabel2.setIcon(new ImageIcon("/Imagenes/gifparado.png"));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLblTitulo = new javax.swing.JLabel();
        jLblTEstudio = new javax.swing.JLabel();
        jLblTDescanso = new javax.swing.JLabel();
        jLblRondas = new javax.swing.JLabel();
        jTxtDescanso = new javax.swing.JTextField();
        jTxtEstudio = new javax.swing.JTextField();
        jTxtRondas = new javax.swing.JTextField();
        jBtnEmpezar = new javax.swing.JButton();
        jBtnPausar = new javax.swing.JButton();
        jBtnDetener = new javax.swing.JButton();
        jLblTemporizador = new javax.swing.JLabel();
        jBtnReanudar = new javax.swing.JButton();
        jLblRondasRestantes = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLblIndicador = new javax.swing.JLabel();
        jBtnPlay = new javax.swing.JButton();
        jBtnStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POMODORO STUDY");
        setBackground(new java.awt.Color(255, 255, 255));
        setFocusable(false);
        setResizable(false);

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setToolTipText("");
        jSeparator1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLblTitulo.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        jLblTitulo.setText("POMODORO STUDY");

        jLblTEstudio.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLblTEstudio.setText("Tiempo de estudio (en minutos):");

        jLblTDescanso.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLblTDescanso.setText("Tiempo descanso (en minutos):");

        jLblRondas.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLblRondas.setText("Número de rondas:");

        jBtnEmpezar.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jBtnEmpezar.setText("EMPEZAR");
        jBtnEmpezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEmpezarActionPerformed(evt);
            }
        });

        jBtnPausar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBtnPausar.setText("PAUSAR");
        jBtnPausar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPausarActionPerformed(evt);
            }
        });

        jBtnDetener.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBtnDetener.setText("DETENER");
        jBtnDetener.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDetenerActionPerformed(evt);
            }
        });

        jLblTemporizador.setFont(new java.awt.Font("Impact", 0, 100)); // NOI18N
        jLblTemporizador.setText("00:00");

        jBtnReanudar.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jBtnReanudar.setText("REANUDAR");
        jBtnReanudar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnReanudarActionPerformed(evt);
            }
        });

        jLblRondasRestantes.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLblRondasRestantes.setText("Rondas restantes: ");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\David y Laura\\Documents\\NetBeansProjects\\PomodoroStudy\\src\\main\\java\\recursos\\icon.png")); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\David y Laura\\Documents\\NetBeansProjects\\PomodoroStudy\\src\\main\\java\\recursos\\spn2.gif")); // NOI18N

        jLblIndicador.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N

        jBtnPlay.setBackground(new java.awt.Color(255, 255, 255));
        jBtnPlay.setIcon(new javax.swing.ImageIcon("C:\\Users\\David y Laura\\Documents\\NetBeansProjects\\PomodoroStudy\\src\\main\\java\\recursos\\play.jpg")); // NOI18N
        jBtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlayActionPerformed(evt);
            }
        });

        jBtnStop.setBackground(new java.awt.Color(255, 255, 255));
        jBtnStop.setIcon(new javax.swing.ImageIcon("C:\\Users\\David y Laura\\Documents\\NetBeansProjects\\PomodoroStudy\\src\\main\\java\\recursos\\pause.jpg")); // NOI18N
        jBtnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnStopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jBtnEmpezar)
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(90, 90, 90))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLblTitulo)
                                .addGap(82, 82, 82))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblTDescanso)
                                    .addComponent(jLblTEstudio)
                                    .addComponent(jLblRondas))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTxtRondas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnStop, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jBtnPausar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnDetener)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBtnReanudar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLblTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblRondasRestantes))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLblIndicador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLblTemporizador)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnPausar)
                            .addComponent(jBtnDetener)
                            .addComponent(jBtnReanudar))
                        .addGap(50, 50, 50)
                        .addComponent(jLblRondasRestantes)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator1)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTitulo)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTEstudio)
                    .addComponent(jTxtEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblTDescanso)
                    .addComponent(jTxtDescanso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblRondas)
                    .addComponent(jTxtRondas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnEmpezar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBtnPlay, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jBtnStop, javax.swing.GroupLayout.Alignment.TRAILING)))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEmpezarActionPerformed
        // TODO add your handling code here:
        try {
            rondas = Integer.parseInt(jTxtRondas.getText());
            m = Integer.parseInt(jTxtEstudio.getText());
            jLblIndicador.setText("TIEMPO DE ESTUDIO");
            t.start();
            t2.start();
            t3.start();
            jLabel2.setIcon(new ImageIcon("D:\\DAVID\\spn2.gif"));
            jBtnEmpezar.setEnabled(false);
            jBtnDetener.setEnabled(true);
            jBtnPausar.setEnabled(true); 
            jBtnReanudar.setEnabled(false);
            jBtnPlay.setEnabled(true);
            jBtnStop.setEnabled(true);
            jLblRondasRestantes.setText("Rondas restantes: "+rondas);
                                    String sonido2 = "D:\\DAVID\\musicaEstudio.wav";
                                    InputStream in;
                                     try {
                                     in = new FileInputStream(sonido2);
                                     audio2 = new AudioStream(in);
                                     AudioPlayer.player.start(audio2);
                                    } catch (FileNotFoundException ex) {
                                        Logger.getLogger(PomodoroStudy.class.getName()).log(Level.SEVERE, null, ex);
                                    } catch (IOException ex) {
                                        Logger.getLogger(PomodoroStudy.class.getName()).log(Level.SEVERE, null, ex);
                                    }
        } catch (NumberFormatException e) { 
            JOptionPane.showMessageDialog(this, "Introduce el tiempo elegido en minutos.", "ERROR", JOptionPane.ERROR_MESSAGE);
            jTxtDescanso.setText("");
            jTxtEstudio.setText("");
            jTxtRondas.setText("");
        }
        //rondas = Integer.parseInt(jTxtRondas.getText());
        //m = Integer.parseInt(jTxtEstudio.getText());
        //t.start();
        //t2.start();
        //t3.start();
        //jLabel2.setIcon(new ImageIcon("D:\\DAVID\\spn2.gif"));
        
        //jBtnEmpezar.setEnabled(false);
        //jBtnDetener.setEnabled(true);
        //jBtnPausar.setEnabled(true); 
        //jBtnReanudar.setEnabled(false);
        //jLblRondasRestantes.setText("Rondas restantes: "+rondas);
    }//GEN-LAST:event_jBtnEmpezarActionPerformed

    private void jBtnPausarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPausarActionPerformed
        // TODO add your handling code here:
        t.stop();
        jBtnPausar.setEnabled(false);
        jBtnReanudar.setEnabled(true);
        jLabel2.setIcon(new ImageIcon("D:\\DAVID\\gifparado.png"));
        AudioPlayer.player.stop(audio2);
    }//GEN-LAST:event_jBtnPausarActionPerformed

    private void jBtnDetenerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDetenerActionPerformed
        // TODO add your handling code here:
        if(t.isRunning())
        {
           t.stop();
           jBtnEmpezar.setEnabled(true);
        }
        jBtnEmpezar.setEnabled(true);
        jBtnDetener.setEnabled(false);
        jBtnPausar.setEnabled(false);
        jBtnReanudar.setEnabled(false);
        jTxtDescanso.setText("");
        jTxtEstudio.setText("");
        m=00;s=00;
        jTxtRondas.setText("");
        actualizarLabel();
        jLblRondasRestantes.setText("Rondas restantes: ");
        jLabel2.setIcon(new ImageIcon("D:\\DAVID\\gifparado.png"));
        AudioPlayer.player.stop(audio2);
        jLblIndicador.setText("");
    }//GEN-LAST:event_jBtnDetenerActionPerformed

    private void jBtnReanudarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnReanudarActionPerformed
        // TODO add your handling code here:
        t.start();
        jBtnReanudar.setEnabled(false);
        jBtnPausar.setEnabled(true);
        jLabel2.setIcon(new ImageIcon("D:\\DAVID\\spn2.gif"));
        AudioPlayer.player.start(audio2);
    }//GEN-LAST:event_jBtnReanudarActionPerformed

    private void jBtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlayActionPerformed
        // TODO add your handling code here:
        if (audio2!=null && t.isRunning()) {
            AudioPlayer.player.start(audio2);
            JOptionPane.showMessageDialog(this, "Audio reanudado correctamente.", "CONTROL AUDIO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnPlayActionPerformed

    private void jBtnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnStopActionPerformed
        // TODO add your handling code here:
        if (audio2!=null && t.isRunning()) {
            AudioPlayer.player.stop(audio2);
            JOptionPane.showMessageDialog(this, "Audio detenido correctamente.", "CONTROL AUDIO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jBtnStopActionPerformed

    private Timer t;
    private Timer t2;
    private Timer t3;
    private int m,s;
    private int rondas;
    private boolean tiempoActivo = false;
    private boolean rondaFinalizada = false;

   private ActionListener acciones = new ActionListener(){   

       @Override
        public void actionPerformed(ActionEvent ae){  
                if(s>0){               
                s--;              
                }else{
                 s=59;
                    if(m>0) m--;
                    else{
                        t.stop();
                        s=00;
                        m=00;
                        tiempoActivo=true;
                        String sonido1 = "D:\\DAVID\\alarma.wav";
                         InputStream in;
                             try {
                                     in = new FileInputStream(sonido1);
                                     AudioStream audio1 = new AudioStream(in);
                                     AudioPlayer.player.start(audio1);
                                    } catch (FileNotFoundException ex) {
                                        Logger.getLogger(PomodoroStudy.class.getName()).log(Level.SEVERE, null, ex);
                                    } catch (IOException ex) {
                                        Logger.getLogger(PomodoroStudy.class.getName()).log(Level.SEVERE, null, ex);
                                    }
                }                
            }actualizarLabel();
        }
    };
   
   private ActionListener acciones2 = new ActionListener(){
       @Override
       public void actionPerformed (ActionEvent ae){
            if (tiempoActivo) {
                    t.start();    
                    tiempoActivo = false;
                    m= Integer.parseInt(jTxtDescanso.getText());
                    AudioPlayer.player.stop(audio2);
                    jLblIndicador.setText("TIEMPO DE DESCANSO");
                    t2.stop();
                    rondaFinalizada = true;
                    rondas--;
                } 
            if (rondas==0) {
                 jBtnEmpezar.setEnabled(true);
                 jBtnDetener.setEnabled(false);
                 jBtnPausar.setEnabled(false);
                 jBtnReanudar.setEnabled(false);
                 jTxtDescanso.setText("");
                 jTxtEstudio.setText("");
                    m=00;s=00;
                 jTxtRondas.setText("");
                 actualizarLabel();
                 jLblRondasRestantes.setText("Rondas restantes: ");
                 jLabel2.setIcon(new ImageIcon("D:\\DAVID\\gifparado.png"));
                 AudioPlayer.player.stop(audio2);
                 jLblIndicador.setText("");
                 JOptionPane.showMessageDialog(null, "¡Enhorabuena, has finalizado tu sesión de estudio!", "SESIÓN FINALIZADA",JOptionPane.INFORMATION_MESSAGE);
           }
       }
   };
   
   private ActionListener acciones3 = new ActionListener(){
       @Override
       public void actionPerformed (ActionEvent ae){
           if (rondaFinalizada==true && tiempoActivo==true && rondas!=0){
            m = Integer.parseInt(jTxtEstudio.getText());
            AudioPlayer.player.start(audio2);
            jLblIndicador.setText("TIEMPO DE ESTUDIO");
            t.start();
            t2.start();
            tiempoActivo=false;
            jLblRondasRestantes.setText("Rondas restantes: "+rondas);
         }
           if (rondas == 0) {
               t3.stop();
               jBtnEmpezar.setEnabled(true);
               jBtnDetener.setEnabled(false);
               jBtnPausar.setEnabled(false);
               jBtnReanudar.setEnabled(false);
               jTxtDescanso.setText("");
               jTxtEstudio.setText("");
               m=00;s=00;
               jTxtRondas.setText("");
               jLblRondasRestantes.setText("Rondas restantes: ");
               jLabel2.setIcon(new ImageIcon("D:\\DAVID\\gifparado.png"));
           }
       }
   
   };

    
    public void actualizarLabel(){
        String fullHour = "";
 
        fullHour += (m > 9) ? /*":" +*/ m : "0" + m;
        fullHour += (s > 9) ? ":" + s : ":0" + s;
        
        jLblTemporizador.setText(fullHour);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PomodoroStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PomodoroStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PomodoroStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PomodoroStudy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new PomodoroStudy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnDetener;
    private javax.swing.JButton jBtnEmpezar;
    private javax.swing.JButton jBtnPausar;
    private javax.swing.JButton jBtnPlay;
    private javax.swing.JButton jBtnReanudar;
    private javax.swing.JButton jBtnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLblIndicador;
    private javax.swing.JLabel jLblRondas;
    private javax.swing.JLabel jLblRondasRestantes;
    private javax.swing.JLabel jLblTDescanso;
    private javax.swing.JLabel jLblTEstudio;
    private javax.swing.JLabel jLblTemporizador;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtDescanso;
    private javax.swing.JTextField jTxtEstudio;
    private javax.swing.JTextField jTxtRondas;
    // End of variables declaration//GEN-END:variables

}
